<!-- JS -->
<script src="{{ asset('public/public/js/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.easing.1.3.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.scrollTo.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.localScroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.viewport.mini.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.parallax-1.1.3.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.fitvids.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.lazyload.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.ajaxchimp.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/jquery.magnific-popup.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/SmoothScroll.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/contact-form.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/owl.carousel.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/isotope.pkgd.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/imagesloaded.pkgd.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/masonry.pkgd.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/wow.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/morphext.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/typed.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/objectFitPolyfill.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/splitting.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/all.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/public/js/custom.js') }}" type="text/javascript"></script>
